print("Gautham Kaarthik")
print("Nithya Lakshmi N")
a=10
b=20
c=a+b
print (c)
firstname = input("Enter your First Name")
lastname = input("Enter your Last Name")
name = firstname+lastname
print("Your Full name is  " +name)
firstnumber=int(input("Enter num1"))
lastnumber=int(input("Enter num2"))
sum=(firstnumber+lastnumber)
print(sum)
firstnumber=int(input("Enter num1"))
lastnumber=int(input("Enter num2"))
diff=(firstnumber-lastnumber)
print(diff)
firstnumber=int(input("Enter num1"))
lastnumber=int(input("Enter num2"))
prod=(firstnumber*lastnumber)
print(prod)
firstnumber=int(input("Enter num1"))
lastnumber=int(input("Enter num2"))
qui=(firstnumber/lastnumber)
print(qui)